server:
  port: 8080  # 端口号
  servlet:
    context-path: /boot001   #项目根路径（前面必须加/）

spring:
  # 项目名称
  application:
    name: boot001
  # 当前配置文件
  profiles:
    active: dev
  # Mysql配置
#  datasource:
#    driver-class-name:  com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/boot001?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#    username: root
#    password: root
  #devtools配置
  devtools:
    restart:
      enabled: true  # 热部署生效
#      additional-paths: scr/main/java  #设置重启目录
      exclude: static  #static目录下文件修改不重启

# Mybatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml #指定Mybatis的Mapper文件
  type-aliases-package: com.jd.boot001.*.entity  #指定Mybatis的实体目录

